# Generated by Django 3.2.22 on 2023-10-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
                ('img', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('insurance_fee', models.IntegerField()),
                ('consultation', models.BooleanField(default=True)),
                ('period_insurance', models.CharField(max_length=200)),
                ('payment_period', models.CharField(max_length=200)),
                ('benefits', models.IntegerField()),
                ('limit_days', models.IntegerField()),
                ('total_limit_days', models.IntegerField()),
                ('advanced_medical_addition', models.CharField(max_length=200)),
                ('contract_age', models.CharField(max_length=200)),
                ('contract_age_addition', models.CharField(max_length=200)),
                ('online', models.BooleanField(default=True)),
                ('offline', models.BooleanField(default=True)),
                ('overview', models.CharField(max_length=200)),
                ('overview_addition', models.CharField(max_length=200)),
                ('document_number', models.CharField(max_length=200)),
            ],
        ),
    ]
