# Generated by Django 3.2.22 on 2023-10-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_nav', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='product',
            new_name='title',
        ),
    ]
